### ISSUE TITLE
使用MaterialApp.router代替MaterialApp时，该如何配置navigatorKey和scaffoldMessengerKey

### ISSUE THREAD

**Issue by xiaobeiy** [Wayaer/flutter_waya#5]
使用MaterialApp.router代替MaterialApp时，MaterialApp.router没有了navigatorKey属性，这种情况下该如何处理。

**Comment by Wayaer** [comment]
```
dependencies:
  flutter:
    sdk: flutter

  go_router: ^13.2.1
```

```
class _MaterialAppRouter extends StatelessWidget {
  _MaterialAppRouter();

  final GoRouter _router =
      GoRouter(navigatorKey: FlExtended().navigatorKey, routes: <RouteBase>[]);

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(routerConfig: _router);
  }
}

```
